### ISSUE TITLE
Not interpreting backslash-escapes for displaying tasks

### ISSUE THREAD

**Issue by tomvdsom** [loweyequeue/alchemist#28]
At least in `--list --verbose`.  Check other places too while we're at it.

Example:

In `alchemist.toml`:

```toml
[tasks.command_escaping]
command = "pri\n|\tf"
args = [",\tdone\n"]

[tasks.shell_escaping]
shell_script = '''
echo "Hello, \t\t\tWorld!\n\n\n"
'''

[tasks.serial_escaping]
serial_tasks = ["o\tn\ne", "t\tw\no", "d\ton\ne"]

[tasks.parallel_escaping]
parallel_tasks = ["o\tn\ne", "t\tw\no", "d\ton\ne"]
```

Output:

![Image](https://github.com/user-attachments/assets/dfec72bc-896d-40d9-b847-acf09c48be1f)
